package com.vini.yoshiescape;

import android.content.Context;
import android.graphics.*;
import android.media.AudioManager;
import android.media.ToneGenerator;
import android.util.SparseArray;
import android.view.MotionEvent;
import android.view.View;
import java.util.*;

public class GameView extends View {
    static final float H=540f,WORLD=6200f,GROUND=455f,START=105f,GOAL=5940f;
    static final int MENU=0,HOW=1,CREDITS=2,PLAY=3,ESCAPE=4,HUNT=5,LAP=6,WIN=7,OVER=8;

    final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG), px=new Paint();
    final List<RectF> solids=new ArrayList<>(), springs=new ArrayList<>(), spikes=new ArrayList<>();
    final List<Ring> rings=new ArrayList<>();
    final SparseArray<PointF> touches=new SparseArray<>();
    final ToneGenerator tone=new ToneGenerator(AudioManager.STREAM_MUSIC,45);

    Bitmap stand; final Bitmap[] run=new Bitmap[4];
    int state=MENU,lap=0,lives=3,ringCount=0,score=0,lastSec=99;
    float x,y,vx,vy,cam,clock,time,safeX,safeY,safeT,inv;
    float yx,yy,yspeed; boolean yActive,toStart=false,sound=true,faceRight=true,grounded=true;
    boolean L,R,A,S,jumpReq; long last;
    String rank="C";

    public GameView(Context c){ super(c); setKeepScreenOn(true); px.setAntiAlias(false); px.setFilterBitmap(false); load(); level(); menu(); }
    Bitmap bm(int id){ return BitmapFactory.decodeResource(getResources(),id); }
    void load(){ stand=bm(R.drawable.mario_stand); run[0]=bm(R.drawable.mario_run1); run[1]=bm(R.drawable.mario_run2); run[2]=bm(R.drawable.mario_run3); run[3]=bm(R.drawable.mario_run4); }
    void ground(float a,float b){ solids.add(new RectF(a,GROUND,b,580)); }
    void plat(float a,float b,float w){ solids.add(new RectF(a,b,a+w,b+24)); }
    void level(){
        ground(0,760);ground(850,1530);ground(1640,2350);ground(2440,3200);ground(3300,4020);ground(4130,4870);ground(4960,WORLD);
        plat(610,372,185);plat(1040,322,210);plat(1375,375,170);plat(1840,345,210);plat(2160,290,210);plat(2660,365,220);plat(3010,315,205);plat(3490,365,190);plat(3780,300,220);plat(4310,355,220);plat(4660,300,215);plat(5230,365,215);plat(5550,310,220);
        springs.add(new RectF(690,GROUND-20,735,GROUND)); springs.add(new RectF(1510,GROUND-20,1555,GROUND)); springs.add(new RectF(3180,GROUND-20,3225,GROUND)); springs.add(new RectF(4850,GROUND-20,4895,GROUND));
        spikes.add(new RectF(1280,GROUND-18,1350,GROUND)); spikes.add(new RectF(2870,GROUND-18,2940,GROUND)); spikes.add(new RectF(4470,GROUND-18,4540,GROUND)); spikes.add(new RectF(5680,GROUND-18,5745,GROUND));
        for(float q=260;q<720;q+=72)addRing(q,390); for(int i=0;i<7;i++)addRing(930+i*70,370-(float)Math.sin(i*Math.PI/6)*115); for(float q=1700;q<2320;q+=78)addRing(q,390); for(int i=0;i<7;i++)addRing(2500+i*82,355-(float)Math.sin(i*Math.PI/6)*100); for(float q=3350;q<3970;q+=82)addRing(q,390); for(int i=0;i<7;i++)addRing(4180+i*92,360-(float)Math.sin(i*Math.PI/6)*105); for(float q=5030;q<5850;q+=84)addRing(q,388);
    }
    void addRing(float a,float b){ rings.add(new Ring(a,b)); }
    void menu(){ state=MENU; touches.clear(); last=System.nanoTime(); invalidate(); }
    void start(){ state=PLAY;lap=0;lives=3;ringCount=0;score=0;x=START;y=GROUND-48;vx=vy=0;cam=0;safeX=x;safeY=y;safeT=0;inv=0;yActive=false;toStart=false;time=50;rank="C";for(Ring r:rings)r.got=false; last=System.nanoTime(); beep(ToneGenerator.TONE_PROP_BEEP,70); }
    public void resumeGameClock(){ last=System.nanoTime(); }

    @Override protected void onDraw(Canvas c){ long n=System.nanoTime();float dt=(n-last)/1e9f;last=n;if(dt<=0||dt>.05f)dt=.016f;clock+=dt;if(playable())update(dt);draw(c);postInvalidateOnAnimation(); }
    boolean playable(){ return state==PLAY||state==ESCAPE||state==HUNT; }

    void update(float dt){
        if(inv>0)inv-=dt;
        float acc=grounded?1900:980,max=S?390:300,fr=grounded?1550:260;
        if(L){vx-=acc*dt;faceRight=false;} if(R){vx+=acc*dt;faceRight=true;} if(!L&&!R){float d=fr*dt;vx=Math.abs(vx)<=d?0:vx-Math.signum(vx)*d;} vx=clamp(vx,-max,max);
        if(jumpReq&&grounded){vy=-615;grounded=false;beep(ToneGenerator.TONE_PROP_BEEP,40);} jumpReq=false; vy=Math.min(920,vy+1540*dt);
        moveX(dt);moveY(dt);spring();collect();hazard();
        if(grounded){safeT+=dt;if(safeT>.7f){safeX=x;safeY=y;safeT=0;}}else safeT=0;
        if(y>630)loseLife();
        if(state==PLAY&&x>GOAL-50)beginLap(1,true);
        if(state==ESCAPE||state==HUNT){time-=dt;int s=Math.max(0,(int)Math.ceil(time));if(s<=10&&s!=lastSec){lastSec=s;beep(ToneGenerator.TONE_PROP_ACK,35);} if(time<=0&&state!=HUNT){state=HUNT;spawnYoshi();beep(ToneGenerator.TONE_CDMA_HIGH_L,300);} boolean hit=toStart?x<START+22:x>GOAL-48;if(hit)lapDone();}
        if(state==HUNT&&yActive)chase(dt);
        float vw=getWidth()>0&&getHeight()>0?getWidth()/(getHeight()/H):960;float t=clamp(x-vw*.42f,0,Math.max(0,WORLD-vw));cam+=(t-cam)*Math.min(1,dt*6);
    }
    void beginLap(int l,boolean left){lap=l;toStart=left;state=l>=3?HUNT:ESCAPE;time=l==1?48:l==2?46:52;lastSec=99;yActive=l>=3;if(yActive)spawnYoshi();beep(l>=3?ToneGenerator.TONE_CDMA_HIGH_L:ToneGenerator.TONE_CDMA_ALERT_CALL_GUARD,180);}
    void lapDone(){vx=vy=0;if(lap>=3){rank="P";score+=5000+ringCount*25;state=WIN;yActive=false;}else state=LAP;}
    void nextLap(){ if(lap==1)beginLap(2,false); else beginLap(3,true); }
    void finish(){rank=lap>=2?(ringCount>=35?"S":"A"):(time>=25&&ringCount>=25?"S":time>=15||ringCount>=18?"A":time>=6?"B":"C");score+=lap*1200+ringCount*20+lives*300;state=WIN;yActive=false;}
    void spawnYoshi(){yActive=true;yspeed=lap>=3?315:260;yx=toStart?Math.min(WORLD-120,x+430):Math.max(30,x-430);yy=GROUND-76;}
    void chase(float dt){float d=Math.signum(x-yx);if(d==0)d=toStart?-1:1;yx+=d*yspeed*dt;yy=GROUND-76+(float)Math.sin(clock*10)*8;yspeed=Math.min(lap>=3?410:360,yspeed+8*dt);if(Math.abs((yx+20)-(x+18))<50&&Math.abs((yy+15)-(y+24))<72){state=OVER;vx=vy=0;beep(ToneGenerator.TONE_CDMA_ABBR_ALERT,280);}}
    void moveX(float dt){x+=vx*dt;RectF r=pr();for(RectF s:solids)if(RectF.intersects(r,s)){if(vx>0)x=s.left-36;else if(vx<0)x=s.right;vx=0;r=pr();}x=clamp(x,0,WORLD-36);}
    void moveY(float dt){float oy=y,ob=y+48;y+=vy*dt;grounded=false;RectF r=pr();for(RectF s:solids)if(RectF.intersects(r,s)){if(vy>=0&&ob<=s.top+14){y=s.top-48;vy=0;grounded=true;}else if(vy<0&&oy>=s.bottom-10){y=s.bottom;vy=0;}r=pr();}}
    RectF pr(){return new RectF(x,y,x+36,y+48);}
    void spring(){for(RectF s:springs)if(RectF.intersects(pr(),s)&&vy>=0){y=s.top-48;vy=-780;grounded=false;beep(ToneGenerator.TONE_PROP_BEEP2,60);}}
    void collect(){float cx=x+18,cy=y+24;for(Ring r:rings)if(!r.got){float dx=r.x-cx,dy=r.y-cy;if(dx*dx+dy*dy<1156){r.got=true;ringCount++;score+=100;}}}
    void hazard(){if(inv>0)return;for(RectF s:spikes)if(RectF.intersects(pr(),s)){if(ringCount>0){ringCount=Math.max(0,ringCount-Math.min(20,ringCount));inv=1.5f;vy=-360;vx=faceRight?-260:260;}else loseLife();beep(ToneGenerator.TONE_PROP_NACK,90);return;}}
    void loseLife(){lives--;if(lives<=0){state=OVER;yActive=false;vx=vy=0;return;}x=safeX;y=safeY;vx=vy=0;inv=1.5f;if(state==ESCAPE||state==HUNT)time=Math.max(0,time-3);}

    void draw(Canvas c){int w=c.getWidth(),h=c.getHeight();if(w<=0||h<=0)return;if(state<=CREDITS){menuScene(c,w,h);if(state==MENU)menuUI(c,w,h);else info(c,w,h,state==HOW);return;}world(c,w,h);hud(c,w,h);if(playable())controls(c,w,h);if(state==LAP)lapUI(c,w,h);else if(state==WIN||state==OVER)result(c,w,h,state==OVER);}
    void world(Canvas c,int w,int h){float sc=h/H;boolean crit=(state==ESCAPE||state==HUNT)&&time<=15;float danger=state==HUNT?1:crit?clamp((15-time)/15,0,1):0;p.setColor(blend(Color.rgb(78,171,242),Color.rgb(45,15,69),danger));c.drawRect(0,0,w,h*.55f,p);p.setColor(blend(Color.rgb(196,235,255),Color.rgb(174,38,47),danger));c.drawRect(0,h*.55f,w,h,p);mountains(c,w,h,danger);float sx=crit?(float)Math.sin(clock*38)*(1.5f+danger*3):0;c.save();c.scale(sc,sc);c.translate(-cam+sx,0);decor(c,danger);platforms(c,danger);rings(c);springs(c);spikes(c);startGate(c);goal(c);player(c);if(yActive)yoshi(c);c.restore();if(crit)danger(c,w,h,danger);}
    void mountains(Canvas c,int w,int h,float d){float sc=h/H;p.setColor(blend(Color.rgb(116,151,192),Color.rgb(48,31,74),d));for(int i=-2;i<9;i++){float q=(i*340-cam*.13f)*sc,b=h*.59f,pk=h*(.29f+(i%2==0?.03f:.09f));Path z=new Path();z.moveTo(q-230*sc,b);z.lineTo(q,pk);z.lineTo(q+230*sc,b);z.close();c.drawPath(z,p);}p.setColor(blend(Color.rgb(47,112,89),Color.rgb(29,24,49),d));for(int i=-2;i<18;i++)c.drawCircle((i*180-cam*.25f)*sc,h*.73f,125*sc,p);}
    void decor(Canvas c,float d){for(float q=180;q<WORLD;q+=370){p.setColor(blend(Color.rgb(36,116,48),Color.rgb(66,31,46),d));c.drawRect(q,415,q+5,GROUND,p);p.setColor(blend(Color.rgb(255,211,62),Color.rgb(245,66,60),d));c.drawRect(q-6,405,q+11,417,p);}}
    void platforms(Canvas c,float d){for(RectF s:solids){p.setColor(blend(Color.rgb(132,77,38),Color.rgb(75,35,39),d));c.drawRect(s,p);float t=28;for(float yy=s.top+10;yy<s.bottom;yy+=t)for(float xx=s.left;xx<s.right;xx+=t){int a=(int)((xx-s.left)/t),b=(int)((yy-s.top)/t);p.setColor(((a+b)&1)==0?blend(Color.rgb(153,91,45),Color.rgb(98,45,45),d):blend(Color.rgb(105,61,34),Color.rgb(52,29,37),d));c.drawRect(xx,yy,Math.min(xx+t,s.right),Math.min(yy+t,s.bottom),p);}p.setColor(blend(Color.rgb(61,177,65),Color.rgb(125,47,48),d));c.drawRect(s.left,s.top,s.right,Math.min(s.bottom,s.top+11),p);p.setColor(blend(Color.rgb(144,231,82),Color.rgb(220,68,50),d));c.drawRect(s.left,s.top,s.right,Math.min(s.bottom,s.top+4),p);}}
    void rings(Canvas c){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(4);for(Ring r:rings)if(!r.got){float k=1+.22f*(float)Math.sin(clock*7+r.x*.02);p.setColor(Color.rgb(255,211,48));c.drawOval(new RectF(r.x-8*k,r.y-13,r.x+8*k,r.y+13),p);}p.setStyle(Paint.Style.FILL);}
    void springs(Canvas c){for(RectF s:springs){p.setColor(Color.rgb(208,31,37));c.drawRect(s.left,s.top,s.right,s.top+8,p);p.setColor(Color.WHITE);for(int i=0;i<3;i++){float yy=s.top+9+i*4;c.drawRect(s.left+7,yy,s.right-7,yy+2,p);}}}
    void spikes(Canvas c){for(RectF s:spikes){p.setColor(Color.LTGRAY);for(float xx=s.left;xx<s.right;xx+=14){Path z=new Path();z.moveTo(xx,s.bottom);z.lineTo(xx+7,s.top);z.lineTo(Math.min(xx+14,s.right),s.bottom);z.close();c.drawPath(z,p);}}}
    void startGate(Canvas c){p.setColor(Color.WHITE);c.drawRect(55,350,65,GROUND,p);c.drawRect(120,350,130,GROUND,p);p.setColor(Color.rgb(132,77,38));c.drawRect(44,330,141,360,p);p.setColor(Color.rgb(255,232,156));p.setTextSize(17);p.setFakeBoldText(true);c.drawText("START",62,351,p);p.setFakeBoldText(false);}
    void goal(Canvas c){p.setColor(Color.LTGRAY);c.drawRect(GOAL,340,GOAL+10,GROUND,p);c.drawRect(GOAL+74,340,GOAL+84,GROUND,p);p.setColor(Color.rgb(119,70,40));c.drawRect(GOAL-8,322,GOAL+92,354,p);p.setColor(Color.rgb(255,226,113));p.setTextSize(17);p.setFakeBoldText(true);c.drawText("GOAL",GOAL+17,345,p);p.setFakeBoldText(false);}
    void player(Canvas c){Bitmap b=stand;if(Math.abs(vx)>28||!grounded)b=run[((int)(clock*(S?13:9)))%4];if(inv>0&&(((int)(clock*16))&1)==0)return;RectF box=new RectF(x-7,y-7,x+43,y+52);if(S&&(!grounded||Math.abs(vx)>55)){c.save();c.rotate((clock*720)%360,box.centerX(),box.centerY());bitmap(c,b,box,!faceRight,true);c.restore();}else bitmap(c,b,box,!faceRight,true);}
    void bitmap(Canvas c,Bitmap b,RectF box,boolean flip,boolean bottom){if(b==null)return;float k=Math.min(box.width()/b.getWidth(),box.height()/b.getHeight()),dw=b.getWidth()*k,dh=b.getHeight()*k,l=box.centerX()-dw/2,t=bottom?box.bottom-dh:box.centerY()-dh/2;RectF d=new RectF(l,t,l+dw,t+dh);c.save();if(flip)c.scale(-1,1,d.centerX(),d.centerY());c.drawBitmap(b,null,d,px);c.restore();}

    void yoshi(Canvas c){boolean chase=state==HUNT&&Math.abs(yx-x)<900, left=x<yx;yoshiSprite(c,yx,yy,chase?1.25f:1f,chase,left);}
    void yoshiSprite(Canvas c,float cx,float cy,float sc,boolean chase,boolean left){boolean aa=p.isAntiAlias();p.setAntiAlias(false);c.save();c.translate(cx,cy);c.scale(left?-sc:sc,sc);p.setColor(Color.rgb(18,24,18));c.drawOval(new RectF(-30,-31,35,28),p);c.drawOval(new RectF(2,-39,48,8),p);p.setColor(Color.rgb(57,190,49));c.drawOval(new RectF(-25,-26,28,24),p);c.drawOval(new RectF(1,-34,44,4),p);p.setColor(Color.rgb(245,230,139));c.drawOval(new RectF(-10,-15,19,22),p);p.setColor(Color.rgb(67,204,55));c.drawOval(new RectF(18,-24,53,4),p);p.setColor(Color.WHITE);if(chase){Path a=new Path();a.moveTo(7,-34);a.lineTo(22,-31);a.lineTo(19,-19);a.lineTo(8,-22);a.close();c.drawPath(a,p);Path b=new Path();b.moveTo(21,-32);b.lineTo(35,-28);b.lineTo(31,-17);b.lineTo(20,-20);b.close();c.drawPath(b,p);}else{c.drawRect(11,-35,21,-20,p);c.drawRect(23,-34,33,-19,p);}p.setColor(Color.BLACK);c.drawRect(16,-28,20,-22,p);c.drawRect(27,-27,31,-21,p);p.setColor(Color.rgb(219,38,34));c.drawRect(-2,-39,5,-30,p);c.drawRect(-10,-34,-3,-25,p);c.drawRect(-15,-26,-8,-17,p);p.setColor(Color.rgb(127,57,35));c.drawRect(-20,-22,3,-12,p);p.setColor(Color.rgb(43,79,145));c.drawRect(-22,-24,5,-21,p);p.setColor(Color.rgb(57,190,49));c.drawRect(-18,15,-9,30,p);c.drawRect(8,14,17,29,p);p.setColor(Color.rgb(234,94,26));c.drawRect(-25,25,-7,35,p);c.drawRect(8,24,27,34,p);p.setColor(Color.rgb(57,190,49));if(chase){c.drawRect(16,-7,48,0,p);c.drawRect(42,-12,55,4,p);c.drawRect(50,-15,58,-8,p);c.drawRect(50,1,57,7,p);}else{c.drawRect(16,-5,30,4,p);c.drawRect(-8,-6,3,5,p);}c.restore();p.setAntiAlias(aa);}

    void danger(Canvas c,int w,int h,float d){float pulse=.45f+.35f*(float)Math.sin(clock*9);p.setColor(Color.argb((int)(55+65*d*pulse),255,20,20));c.drawRect(0,0,w,h,p);p.setColor(Color.argb((int)(150+70*pulse),255,40,40));float q=Math.max(7,h*.014f);c.drawRect(0,0,w,q,p);c.drawRect(0,h-q,w,h,p);}
    String prRank(){if(lap>=3)return"P";if(lap>=2)return ringCount>=35?"S":"A";if(ringCount>=30)return"S";if(ringCount>=18)return"A";if(ringCount>=8)return"B";return"C";}
    void hud(Canvas c,int w,int h){float d=Math.max(12,h*.022f);p.setColor(Color.argb(190,7,18,36));c.drawRoundRect(d,d,w-d,d+h*.115f,14,14,p);p.setFakeBoldText(true);p.setTextSize(Math.max(17,h*.037f));p.setColor(Color.rgb(255,226,70));c.drawText("TIME",d*1.6f,d+h*.047f,p);p.setColor(Color.WHITE);c.drawText(state==PLAY?"--":String.format("%02d",Math.max(0,(int)Math.ceil(time))),d*5.4f,d+h*.047f,p);p.setColor(Color.rgb(255,226,70));c.drawText("RINGS",d*1.6f,d+h*.094f,p);p.setColor(Color.WHITE);c.drawText(String.format("%03d",ringCount),d*6.2f,d+h*.094f,p);float m=w*.49f;c.drawText("LIVES "+lives,m-95,d+h*.047f,p);c.drawText("LAP "+Math.max(1,lap==0?1:lap),m-95,d+h*.094f,p);p.setColor(Color.rgb(255,226,70));p.setTextAlign(Paint.Align.RIGHT);c.drawText("RANK "+prRank(),w-d*1.7f,d+h*.063f,p);p.setTextAlign(Paint.Align.LEFT);p.setColor(Color.WHITE);p.setTextSize(Math.max(14,h*.027f));String s=state==PLAY?"CHEGUE AO GOAL →":toStart?"ESCAPE ← VOLTE AO START":"LAP → CORRA AO GOAL";c.drawText(s,w-d*17,d+h*.102f,p);p.setFakeBoldText(false);if(state==HUNT&&yActive){float dist=Math.abs(yx-x);p.setColor(Color.argb(205,70,0,10));float bw=Math.min(w*.34f,360);c.drawRoundRect(w/2f-bw/2,h*.145f,w/2f+bw/2,h*.21f,12,12,p);p.setColor(Color.WHITE);p.setTextAlign(Paint.Align.CENTER);p.setFakeBoldText(true);p.setTextSize(Math.max(15,h*.029f));c.drawText("YOSHI  "+Math.round(dist)+" px  •  CORRE!",w/2f,h*.187f,p);p.setTextAlign(Paint.Align.LEFT);p.setFakeBoldText(false);}}
    void controls(Canvas c,int w,int h){float r=Math.max(42,h*.084f),yy=h-r*1.25f,lx=r*1.25f,rx=lx+r*2.45f,jx=w-r*1.25f,sx=jx-r*2.65f;btn(c,lx,yy,r,L,"◀");btn(c,rx,yy,r,R,"▶");btn(c,sx,yy,r*.88f,S,"GIRO");btn(c,jx,yy,r*1.03f,A,"A");}
    void btn(Canvas c,float x,float y,float r,boolean on,String t){p.setColor(on?Color.argb(175,255,255,255):Color.argb(78,7,18,36));c.drawCircle(x,y,r,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2.5f);p.setColor(Color.argb(205,255,255,255));c.drawCircle(x,y,r,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.WHITE);p.setTextAlign(Paint.Align.CENTER);p.setFakeBoldText(true);p.setTextSize(t.equals("GIRO")?r*.33f:r*.58f);Paint.FontMetrics f=p.getFontMetrics();c.drawText(t,x,y-(f.ascent+f.descent)/2,p);p.setTextAlign(Paint.Align.LEFT);p.setFakeBoldText(false);}

    void menuScene(Canvas c,int w,int h){p.setColor(Color.rgb(72,164,238));c.drawRect(0,0,w/2f,h,p);p.setColor(Color.rgb(32,18,51));c.drawRect(w/2f,0,w,h,p);p.setColor(Color.rgb(82,181,72));Path a=new Path();a.moveTo(0,h*.72f);a.lineTo(w*.17f,h*.35f);a.lineTo(w*.5f,h*.72f);a.close();c.drawPath(a,p);p.setColor(Color.rgb(95,31,42));Path b=new Path();b.moveTo(w*.5f,h*.72f);b.lineTo(w*.78f,h*.3f);b.lineTo(w,h*.72f);b.close();c.drawPath(b,p);bitmap(c,run[((int)(clock*8))%4],new RectF(w*.28f,h*.42f,w*.39f,h*.72f),false,true);yoshiSprite(c,w*.80f,h*.50f,Math.max(2.2f,h/240f),true,true);p.setTextAlign(Paint.Align.CENTER);p.setFakeBoldText(true);p.setColor(Color.rgb(116,238,66));p.setTextSize(Math.max(46,h*.12f));c.drawText("YOSHI",w/2f,h*.22f,p);p.setColor(Color.rgb(255,201,48));c.drawText("ESCAPE",w/2f,h*.34f,p);p.setTextAlign(Paint.Align.LEFT);p.setFakeBoldText(false);}
    void menuUI(Canvas c,int w,int h){float cw=Math.min(520,w*.47f),ch=Math.min(270,h*.52f),l=(w-cw)/2,t=h*.42f;p.setColor(Color.argb(235,246,246,235));c.drawRoundRect(l,t,l+cw,t+ch,18,18,p);String[] it={"START","OPTIONS  •  SOM "+(sound?"ON":"OFF"),"HOW TO PLAY","CREDITS"};p.setTextAlign(Paint.Align.CENTER);p.setFakeBoldText(true);p.setTextSize(Math.max(23,h*.049f));for(int i=0;i<4;i++){float yy=t+58+i*(ch-85)/3;p.setColor(Color.rgb(30,34,42));c.drawText(it[i],w/2f,yy,p);}p.setTextAlign(Paint.Align.LEFT);p.setFakeBoldText(false);}
    void info(Canvas c,int w,int h,boolean how){p.setColor(Color.argb(225,4,12,25));c.drawRect(0,0,w,h,p);float l=w*.18f,r=w*.82f,t=h*.18f,b=h*.82f;p.setColor(Color.rgb(245,245,235));c.drawRoundRect(l,t,r,b,22,22,p);p.setTextAlign(Paint.Align.CENTER);p.setFakeBoldText(true);p.setColor(Color.rgb(25,35,48));p.setTextSize(Math.max(28,h*.06f));c.drawText(how?"HOW TO PLAY":"CREDITS",w/2f,t+60,p);p.setTextSize(Math.max(16,h*.032f));p.setFakeBoldText(false);String[] z=how?new String[]{"Chegue ao Goal e escape de volta ao Start.","Pegue rings, use molas e evite espinhos.","Lap 2 aumenta o risco. Lap 3 libera o Yoshi.","Yoshi encostou em você = fim da tentativa."}:new String[]{"Fangame pessoal / beta mobile.","Game design: Vini + ChatGPT.","Conceitos visuais fornecidos pelo usuário.","Beta v0.2"};float yy=t+120;for(String q:z){c.drawText(q,w/2f,yy,p);yy+=44;}p.setFakeBoldText(true);p.setColor(Color.rgb(35,132,196));c.drawText("TOQUE PARA VOLTAR",w/2f,b-36,p);p.setTextAlign(Paint.Align.LEFT);p.setFakeBoldText(false);}
    void lapUI(Canvas c,int w,int h){p.setColor(Color.argb(210,3,11,24));c.drawRect(0,0,w,h,p);float cw=Math.min(w*.74f,760),ch=Math.min(h*.58f,360),l=(w-cw)/2,t=(h-ch)/2;p.setColor(Color.rgb(17,37,62));c.drawRoundRect(l,t,l+cw,t+ch,26,26,p);p.setTextAlign(Paint.Align.CENTER);p.setFakeBoldText(true);p.setColor(Color.rgb(255,211,55));p.setTextSize(Math.max(34,h*.075f));c.drawText("LAP "+lap+" COMPLETE",w/2f,t+ch*.28f,p);p.setColor(Color.WHITE);p.setTextSize(Math.max(16,h*.033f));c.drawText(lap==1?"Finalizar ou arriscar Lap 2 para subir o rank?":"Quer Rank P? Lap 3 solta o Yoshi.",w/2f,t+ch*.45f,p);float by=t+ch*.67f,bw=cw*.34f;p.setColor(Color.rgb(63,153,91));c.drawRoundRect(w/2f-bw-14,by,w/2f-14,by+64,14,14,p);p.setColor(lap==2?Color.rgb(178,35,48):Color.rgb(54,111,195));c.drawRoundRect(w/2f+14,by,w/2f+bw+14,by+64,14,14,p);p.setColor(Color.WHITE);p.setTextSize(Math.max(17,h*.036f));c.drawText("FINALIZAR",w/2f-bw/2-14,by+42,p);c.drawText(lap==1?"LAP 2":"LAP 3",w/2f+bw/2+14,by+42,p);p.setTextAlign(Paint.Align.LEFT);p.setFakeBoldText(false);}
    void result(Canvas c,int w,int h,boolean over){p.setColor(Color.argb(215,3,11,24));c.drawRect(0,0,w,h,p);float cw=Math.min(w*.68f,700),ch=Math.min(h*.62f,390),l=(w-cw)/2,t=(h-ch)/2;p.setColor(Color.rgb(12,35,61));c.drawRoundRect(l,t,l+cw,t+ch,30,30,p);p.setTextAlign(Paint.Align.CENTER);p.setFakeBoldText(true);p.setColor(over?Color.rgb(255,95,80):rank.equals("P")?Color.rgb(255,100,220):Color.rgb(246,200,60));p.setTextSize(Math.max(36,h*.105f));c.drawText(over?"RUN OVER":"RANK "+rank,w/2f,t+ch*.34f,p);p.setColor(Color.WHITE);p.setTextSize(Math.max(16,h*.034f));c.drawText(over?(yActive?"Yoshi alcançou o Mario.":"Você ficou sem vidas."):"LAP "+lap+"  •  RINGS "+ringCount+"  •  SCORE "+score,w/2f,t+ch*.55f,p);p.setColor(Color.rgb(95,213,255));c.drawText("TOQUE PARA VOLTAR AO MENU",w/2f,t+ch*.78f,p);p.setTextAlign(Paint.Align.LEFT);p.setFakeBoldText(false);}

    @Override public boolean onTouchEvent(MotionEvent e){int a=e.getActionMasked(),i=e.getActionIndex();if(a==MotionEvent.ACTION_DOWN){float tx=e.getX(i),ty=e.getY(i);if(state==MENU){menuTap(tx,ty);return true;}if(state==HOW||state==CREDITS){state=MENU;return true;}if(state==LAP){lapTap(tx,ty);return true;}if(state==WIN||state==OVER){menu();return true;}}if(!playable())return true;if(a==MotionEvent.ACTION_DOWN||a==MotionEvent.ACTION_POINTER_DOWN)touches.put(e.getPointerId(i),new PointF(e.getX(i),e.getY(i)));else if(a==MotionEvent.ACTION_MOVE)for(int k=0;k<e.getPointerCount();k++){int id=e.getPointerId(k);PointF q=touches.get(id);if(q==null){q=new PointF();touches.put(id,q);}q.set(e.getX(k),e.getY(k));}else if(a==MotionEvent.ACTION_UP||a==MotionEvent.ACTION_POINTER_UP)touches.remove(e.getPointerId(i));else if(a==MotionEvent.ACTION_CANCEL)touches.clear();recalc();return true;}
    void menuTap(float x,float y){float h=getHeight(),w=getWidth(),ch=Math.min(270,h*.52f),t=h*.42f,row=(ch-85)/3;float[] q={t+58,t+58+row,t+58+2*row,t+58+3*row};int s=-1;for(int i=0;i<4;i++)if(Math.abs(y-q[i])<30&&x>w*.27f&&x<w*.73f)s=i;if(s==0)start();else if(s==1){sound=!sound;beep(ToneGenerator.TONE_PROP_BEEP,40);}else if(s==2)state=HOW;else if(s==3)state=CREDITS;}
    void lapTap(float x,float y){float w=getWidth(),h=getHeight(),ch=Math.min(h*.58f,360),t=(h-ch)/2,by=t+ch*.67f;if(y<by-12||y>by+80)return;if(x<w/2f)finish();else nextLap();}
    void recalc(){float w=getWidth(),h=getHeight(),r=Math.max(42,h*.084f),yy=h-r*1.25f,lx=r*1.25f,rx=lx+r*2.45f,jx=w-r*1.25f,sx=jx-r*2.65f;boolean nl=false,nr=false,na=false,ns=false;for(int i=0;i<touches.size();i++){PointF q=touches.valueAt(i);if(in(q,lx,yy,r*1.05f))nl=true;if(in(q,rx,yy,r*1.05f))nr=true;if(in(q,jx,yy,r*1.10f))na=true;if(in(q,sx,yy,r*.98f))ns=true;}if(na&&!A)jumpReq=true;L=nl;R=nr;A=na;S=ns;}
    boolean in(PointF q,float x,float y,float r){float a=q.x-x,b=q.y-y;return a*a+b*b<=r*r;}
    int blend(int a,int b,float t){t=clamp(t,0,1);return Color.rgb((int)(Color.red(a)+(Color.red(b)-Color.red(a))*t),(int)(Color.green(a)+(Color.green(b)-Color.green(a))*t),(int)(Color.blue(a)+(Color.blue(b)-Color.blue(a))*t));}
    float clamp(float v,float a,float b){return Math.max(a,Math.min(b,v));}
    void beep(int t,int ms){if(sound)try{tone.startTone(t,ms);}catch(Exception ignored){}}
    @Override protected void onDetachedFromWindow(){super.onDetachedFromWindow();tone.release();}
    static class Ring{final float x,y;boolean got;Ring(float a,float b){x=a;y=b;}}
}
